#!/bin/bash

# Error flags configuration for bash
set -o errexit
set -o pipefail
set -o nounset

# Launching migrations and the server
python src/manage.py migrate
python src/manage.py runserver 0.0.0.0:8000
