volumes:
  locamind_local_db_data: {}

services:
  django: &django
    build: 
      context: .
      dockerfile: /docker/local/django/Dockerfile
    image: locamind_local_django
    container_name: locamind_local_django
    volumes:
      - .:/project
    ports:
      - 8000:8000
    env_file:
      - ./.env
    command: /start
    depends_on:
      - postgres
      - redis
      - mailpit

  postgres:
    image: postgres:16-alpine
    container_name: locamind_local_postgres
    volumes:
      - locamind_local_db_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: locamind_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: redis:alpine
    container_name: locamind_local_redis
    ports:
      - 6379:6379
  
  celeryworker:
    <<: *django
    image: locamind_local_celeryworker
    container_name:  locamind_local_celeryworker
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: locamind_local_celerybeat
    container_name:  locamind_local_celerybeat
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: locamind_local_flower
    container_name:  locamind_local_flower
    ports:
      - 5555:5555
    command: /start-flower
    depends_on:
      - redis
      - django
      - celeryworker
      - celerybeat
