[project]
name = "BienLocation"
version = "0.1.0"
description = "Free online rental property management service for private landlords."
authors = [
    {name = "Macktireh", email = "mack.abdisoubaneh@gmail.com"},
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}
dependencies = [
    "django>=5.0.6",
]

[tool.pdm.dev-dependencies]
dev = [
    "django-browser-reload>=1.12.1",
    "django-debug-toolbar>=4.3.0",
    "django-extensions>=3.2.3",
    "pre-commit>=3.7.1",
    "ruff>=0.4.4",
]


[tool.pdm]
distribution = false
