[project]
name = "BienLocation"
version = "0.1.0"
description = "Free online rental property management service for private landlords."
authors = [
    {name = "Macktireh", email = "mack.abdisoubaneh@gmail.com"},
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}
dependencies = [
    "django>=5.0.6",
    "django-environ>=0.11.2",
    "whitenoise>=6.6.0",
]

[tool.pdm.dev-dependencies]
dev = [
    "django-browser-reload>=1.12.1",
    "django-debug-toolbar>=4.3.0",
    "django-extensions>=3.2.3",
    "pre-commit>=3.7.1",
    "ruff>=0.4.4",
]


[tool.pdm]
distribution = false


[tool.pdm.scripts]
newapp = "python manage.py startapp"
makemigrations = "python manage.py makemigrations"
migrate = "python manage.py migrate"
start = "python manage.py runserver"
test = "python manage.py test -v 2"
shell = "python manage.py shell"
createsuperuser = "python manage.py createsuperuser --email=admin@example.com --first_name=Admin --last_name=AD"
collectstatic = "python manage.py collectstatic"
loaddata = "python manage.py loaddata"
dumpdata = "python manage.py dumpdata"
stripe_sync = "python manage.py djstripe_sync_models"
tailwind = "pnpm run tailwind"
rufffix = "ruff --fix --exit-zero ."
ruffformat = "ruff format ."
ruffcheck = "ruff check ."
mmm = {composite = ["makemigrations", "migrate"]}
dev = {composite = ["tailwind", "start"]}
ruff = {composite = ["rufffix", "ruffformat", "ruffcheck"]}


[tool.ruff]
line-length = 120
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

