# Generated by Django 5.0.6 on 2024-06-29 15:36

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name="Public ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date time on which the object was created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date time on which the object was updated.", verbose_name="Updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("READY", "Ready"), ("SENDING", "Sending"), ("SENT", "Sent"), ("FAILED", "Failed")],
                        db_index=True,
                        default="READY",
                        max_length=255,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("plain_text", models.TextField(blank=True)),
                ("html", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="emails", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Emails",
                "db_table": "emails",
                "indexes": [models.Index(fields=["id"], name="id_idx")],
            },
        ),
    ]
